spring:
  datasource:
    url: jdbc:mysql://192.168.10.10:3306/shop?useSSL=false&useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    username: homestead
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 192.168.10.10
    port: 6379